# Trading AI Agent Configuration

# API Keys (добавьте свои ключи)
api:
  fundingpips:
    api_key: "YOUR_FUNDINGPIPS_API_KEY"
    secret_key: "YOUR_FUNDINGPIPS_SECRET"
    base_url: "https://api.fundingpips.com"
  
  hashhedge:
    api_key: "YOUR_HASHHEDGE_API_KEY"
    secret_key: "YOUR_HASHHEDGE_SECRET"
    base_url: "https://api.hashhedge.com"
  
  telegram:
    bot_token: "YOUR_TELEGRAM_BOT_TOKEN"
    chat_id: "YOUR_TELEGRAM_CHAT_ID"

# Database
database:
  type: "sqlite"  # sqlite или postgresql
  url: "sqlite:///data/trading_agent.db"
  echo: false
  # Для PostgreSQL:
  # type: "postgresql"
  # url: "postgresql://user:password@localhost:5432/trading_agent"
  # host: "localhost"
  # port: 5432
  # name: "trading_agent"
  # user: "postgres"
  # password: "password"

# Orchestration Database (PostgreSQL)
orchestration:
  database:
    url: "postgresql://katya@localhost:5432/gregory_orchestration"
    echo: false
  
  # n8n Integration
  n8n:
    webhook_secret: "webhook_secret_change_me"
    allowed_ips: ["127.0.0.1", "172.16.0.0/12"]  # Docker networks
    base_url: "http://localhost:5678"
  
  # Artifacts Storage
  artifacts:
    root_path: "./artifacts"
    s3:
      endpoint: ""  # Для будущего использования
      bucket: ""
      access_key: ""
      secret_key: ""
  
  # Quality Thresholds для Metrics Guard
  quality_thresholds:
    default:
      min_sharpe: 1.0
      max_drawdown: 0.20
      max_staleness_hours: 4
      min_trade_count: 10
    
    strategies:
      eurusd_mtf:
        min_sharpe: 1.2
        max_drawdown: 0.15
        max_staleness_hours: 2
      
      btcusd_momentum:
        min_sharpe: 1.0
        max_drawdown: 0.25
        max_staleness_hours: 1
  
  # Concurrency Settings
  concurrency:
    nightly_retrain: 1      # Только одно обучение одновременно
    run_strategy: 10        # До 10 стратегий параллельно
    upload_deploy: 3        # До 3 загрузок одновременно
    metrics_guard: 1        # Один guard
  
  # Retry Policy
  retry:
    max_attempts: 3
    backoff_factor: 2       # 2, 4, 8 секунд
    max_delay: 300          # 5 минут максимум

# Security Configuration
security:
  webhook:
    secret_key: "your_webhook_secret_key_change_me"
    allowed_ips: 
      - "127.0.0.1"
      - "172.16.0.0/12"  # Docker networks
      - "10.0.0.0/8"     # Private networks
    max_timestamp_diff: 300  # 5 minutes
  
  rate_limit:
    max_requests: 100
    window_seconds: 3600  # 1 hour
    burst_limit: 10
    burst_window: 60  # 1 minute
  
  retry:
    max_attempts: 3
    base_delay: 1.0
    max_delay: 300.0
    backoff_factor: 2.0
    strategy: "exponential"
    jitter: true
  
  idempotency:
    cache_ttl: 3600  # 1 hour
    max_cache_size: 10000
  
  backpressure:
    max_queue_size: 1000
    queue_full_threshold: 0.8
    delay: 0.1

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  docs_enabled: true
  cors:
    allow_origins: ["*"]
  trusted_hosts: ["*"]

# Trading Configuration
trading:
  # Таймфреймы для анализа (в порядке приоритета)
  timeframes:
    - "4h"  # Тренд
    - "1h"  # Подтверждение
    - "5m"  # Вход
  
  # Активы для торговли
  assets:
    forex:
      - "EURUSD"
      - "GBPUSD"
      - "USDJPY"
    crypto:
      - "BTCUSDT"
      - "ETHUSDT"
      - "ADAUSDT"
  
  # Настройки риска
  risk:
    max_position_size: 0.02  # 2% от депозита
    stop_loss_pct: 0.01      # 1% стоп-лосс
    take_profit_pct: 0.02    # 2% тейк-профит

# ML Configuration
ml:
  # Параметры обучения
  training:
    test_size: 0.2
    validation_size: 0.1
    random_state: 42
  
  # Модели
  models:
    - name: "xgboost"
      params:
        n_estimators: 100
        max_depth: 6
        learning_rate: 0.1
    
    - name: "lightgbm"
      params:
        n_estimators: 100
        max_depth: 6
        learning_rate: 0.1

# Technical Indicators
indicators:
  sma:
    periods: [20, 50, 200]
  ema:
    periods: [12, 26]
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  bollinger:
    period: 20
    std_dev: 2
  macd:
    fast: 12
    slow: 26
    signal: 9

# Dashboard
dashboard:
  host: "0.0.0.0"
  port: 8501
  debug: false
  auto_reload: true

# Logging
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
  file: "logs/trading_agent.log"
  max_size: "10 MB"
  retention: "30 days"

# Backtesting
backtesting:
  start_date: "2023-01-01"
  end_date: "2023-12-31"
  initial_capital: 10000
  commission: 0.001  # 0.1%

